<?php

namespace common\modules\testimonial\controllers;

use Yii;
use yii\base\Model;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\modules\testimonial\models\Testimonial;
use yeesoft\controllers\admin\BaseController;
use yeesoft\models\User;

/**
 * TestimonialController implements the CRUD actions for Testimonial model.
 */
class DefaultController extends BaseController
{

    public function init()
    {
        $this->layout = '@app/views/layouts/admin/main.php';
        $this->modelClass = $this->module->testimonialModelClass;
        $this->modelSearchClass = $this->module->testimonialModelSearchClass;

        $this->indexView = $this->module->indexView;
        $this->viewView = $this->module->viewView;
        $this->createView = $this->module->createView;
        $this->updateView = $this->module->updateView;

        parent::init();
    }

    protected function getRedirectPage($action, $model = null)
    {
        if (!User::hasPermission('editTestimonials') && $action == 'create') {
            return ['view', 'id' => $model->id];
        }

        switch ($action) {
            case 'update':
                return ['update', 'id' => $model->id];
                break;
            case 'create':
                return ['update', 'id' => $model->id];
                break;
            default:
                return parent::getRedirectPage($action, $model);
        }
    }

    public function actionCreate()
    {
        return parent::actionCreate(); // TODO: Change the autogenerated stub
    }

    public function actionUpdate($id)
    {
        return parent::actionUpdate($id); // TODO: Change the autogenerated stub
    }

}
